import type { ImportEntityType, ImportField } from "@/services/import/import.types";

export const MAX_IMPORT_FILE_SIZE = 10 * 1024 * 1024;
export const IMPORT_BATCH_SIZE = 100;
export const MAX_STORED_ROW_ERRORS = 250;
export const PREVIEW_ROW_LIMIT = 20;

export const IMPORT_FIELDS: Record<ImportEntityType, ImportField[]> = {
  CUSTOMERS: [
    { key: "fullName", label: "نام کامل مشتری", required: true, aliases: ["name", "full name", "fullname", "customer", "musteri", "musteri adi", "ad soyad", "اسم", "نام"] },
    { key: "phone", label: "تلفن", required: true, aliases: ["phone", "mobile", "gsm", "telefon", "telephone", "whatsapp phone", "شماره", "تلفن"] },
    { key: "whatsapp", label: "واتساپ", aliases: ["whatsapp", "wa", "واتساپ"] },
    { key: "email", label: "ایمیل", aliases: ["email", "mail", "e-mail", "ایمیل"] },
    { key: "nationality", label: "ملیت", aliases: ["nationality", "country", "ملیت"] },
    { key: "language", label: "زبان", aliases: ["language", "lang", "زبان"] },
    { key: "source", label: "منبع", aliases: ["source", "lead source", "منبع"] },
    { key: "assignedAgentId", label: "شناسه مشاور", aliases: ["assignedAgentId", "agent id", "consultant id"] },
    { key: "assignedAgentEmail", label: "ایمیل مشاور", technical: true, aliases: ["agent_email", "agent email", "consultant email", "assigned agent email", "ایمیل مشاور"] },
    { key: "interestedCity", label: "شهر هدف", aliases: ["city", "sehir", "şehir", "interested city", "شهر"] },
    { key: "interestedDistrict", label: "منطقه هدف", aliases: ["district", "ilce", "ilçe", "interested district", "منطقه"] },
    { key: "transactionType", label: "نوع معامله", aliases: ["transaction", "transaction type", "sale rent", "نوع معامله"] },
    { key: "propertyType", label: "نوع ملک", aliases: ["property type", "type", "نوع ملک"] },
    { key: "minBudget", label: "حداقل بودجه", aliases: ["min budget", "budget min", "حداقل بودجه"] },
    { key: "maxBudget", label: "حداکثر بودجه", aliases: ["budget", "max budget", "butce", "bütçe", "price limit", "بودجه"] },
    { key: "currency", label: "ارز", aliases: ["currency", "money", "ارز"] },
    { key: "minRooms", label: "حداقل اتاق", aliases: ["min rooms", "rooms min"] },
    { key: "maxRooms", label: "حداکثر اتاق", aliases: ["rooms", "max rooms", "oda", "اتاق"] },
    { key: "minArea", label: "حداقل متراژ", aliases: ["min area", "area min"] },
    { key: "maxArea", label: "حداکثر متراژ", aliases: ["area", "max area", "sqm", "m2"] },
    { key: "citizenshipInterest", label: "علاقه به شهروندی", aliases: ["citizenship", "passport", "شهروندی"] },
    { key: "investmentInterest", label: "سرمایه گذاری", aliases: ["investment", "invest", "سرمایه"] },
    { key: "residenceInterest", label: "علاقه به اقامت", aliases: ["residence", "residency", "اقامت"] },
    { key: "notes", label: "یادداشت", aliases: ["notes", "note", "comment", "یادداشت"] },
    { key: "tags", label: "تگ ها", aliases: ["tags", "tag", "برچسب"] },
    { key: "status", label: "وضعیت", aliases: ["status", "وضعیت"] },
    { key: "nextFollowUp", label: "پیگیری بعدی", aliases: ["next follow up", "followup", "پیگیری"] },
  ],
  PROPERTIES: [
    { key: "title", label: "عنوان", required: true, aliases: ["title", "name", "property title", "عنوان", "نام"] },
    { key: "propertyCode", label: "کد ملک", required: true, aliases: ["property code", "propertyCode", "code", "reference", "ref", "کد"] },
    { key: "description", label: "توضیحات", aliases: ["description", "desc", "توضیحات"] },
    { key: "transactionType", label: "نوع معامله", required: true, aliases: ["transaction", "transaction type", "sale rent", "نوع معامله"] },
    { key: "propertyType", label: "نوع ملک", required: true, aliases: ["property type", "type", "نوع ملک"] },
    { key: "status", label: "وضعیت", aliases: ["status", "وضعیت"] },
    { key: "projectId", label: "شناسه پروژه", aliases: ["project id", "projectId"] },
    { key: "projectName", label: "نام پروژه", technical: true, aliases: ["project", "project name", "نام پروژه"] },
    { key: "assignedAgentId", label: "شناسه مشاور", aliases: ["agent id", "assignedAgentId"] },
    { key: "assignedAgentEmail", label: "ایمیل مشاور", technical: true, aliases: ["agent_email", "agent email", "assigned agent email"] },
    { key: "city", label: "شهر", required: true, aliases: ["city", "sehir", "şehir", "شهر"] },
    { key: "district", label: "منطقه", aliases: ["district", "ilce", "ilçe", "منطقه"] },
    { key: "neighborhood", label: "محله", aliases: ["neighborhood", "محله"] },
    { key: "price", label: "قیمت", aliases: ["price", "amount", "قیمت"] },
    { key: "currency", label: "ارز", aliases: ["currency", "ارز"] },
    { key: "rooms", label: "اتاق", aliases: ["rooms", "room", "oda", "اتاق"] },
    { key: "bathrooms", label: "حمام", aliases: ["bathrooms", "bath", "حمام"] },
    { key: "grossArea", label: "متراژ ناخالص", aliases: ["gross area", "area", "sqm", "m2", "متراژ"] },
    { key: "netArea", label: "متراژ خالص", aliases: ["net area"] },
    { key: "floor", label: "طبقه", aliases: ["floor", "طبقه"] },
    { key: "totalFloors", label: "کل طبقات", aliases: ["total floors"] },
    { key: "buildingAge", label: "سن بنا", aliases: ["building age", "age"] },
    { key: "furnished", label: "مبله", aliases: ["furnished", "furniture", "مبله"] },
    { key: "balcony", label: "بالکن", aliases: ["balcony", "بالکن"] },
    { key: "parking", label: "پارکینگ", aliases: ["parking", "پارکینگ"] },
    { key: "pool", label: "استخر", aliases: ["pool", "استخر"] },
    { key: "citizenshipSuitable", label: "مناسب شهروندی", aliases: ["citizenship", "شهروندی"] },
    { key: "residencePermitSuitable", label: "مناسب اقامت", aliases: ["residence permit", "اقامت"] },
    { key: "socialFacilities", label: "امکانات اجتماعی", aliases: ["facilities", "social facilities", "امکانات"] },
    { key: "source", label: "منبع", aliases: ["source", "منبع"] },
    { key: "sourceUrl", label: "لینک منبع", aliases: ["source url", "url"] },
    { key: "videoUrl", label: "ویدیو", aliases: ["video", "video url"] },
  ],
  PROJECTS: [
    { key: "name", label: "نام پروژه", required: true, aliases: ["name", "project", "project name", "نام"] },
    { key: "developer", label: "سازنده", aliases: ["developer", "builder", "سازنده"] },
    { key: "description", label: "توضیحات", aliases: ["description", "desc", "توضیحات"] },
    { key: "city", label: "شهر", required: true, aliases: ["city", "sehir", "şehir", "شهر"] },
    { key: "district", label: "منطقه", aliases: ["district", "ilce", "ilçe", "منطقه"] },
    { key: "deliveryDate", label: "تاریخ تحویل", aliases: ["delivery", "delivery date", "تحویل"] },
    { key: "paymentPlan", label: "شرایط پرداخت", aliases: ["payment", "payment plan", "پرداخت"] },
    { key: "citizenshipSuitable", label: "مناسب شهروندی", aliases: ["citizenship", "شهروندی"] },
    { key: "residenceSuitable", label: "مناسب اقامت", aliases: ["residence", "اقامت"] },
    { key: "facilities", label: "امکانات", aliases: ["facilities", "amenities", "امکانات"] },
    { key: "status", label: "وضعیت", aliases: ["status", "وضعیت"] },
  ],
};

export function getImportFields(entityType: ImportEntityType) {
  return IMPORT_FIELDS[entityType];
}
